set linesize 1500
col OWNER for a20
col LAST_DDL_ for a20
col COMPILAR for a80
col OBJECT_TYPE for a20
col OBJECT_NAME form a40
SELECT OWNER, OBJECT_TYPE, OBJECT_NAME, LAST_DDL_TIME,
DECODE( OBJECT_TYPE, 'PACKAGE BODY','ALTER PACKAGE '||OWNER||'.'||OBJECT_NAME||' COMPILE BODY;','ALTER '||OBJECT_TYPE||' '||OWNER||'.'||OBJECT_NAME||' COMPILE;') COMPILAR
FROM DBA_OBJECTS
WHERE STATUS != 'VALID'
and owner not in ('OLAPSYS', 'SYS','SYSTEM','ORDDATA','MDSYS','SYS_CONSULTA','SMARTLOGIC','SYSMAN','PUBLIC','APEX_030200','PERFSTAT' )
ORDER BY LAST_DDL_TIME;

--set linesize 1500
--col OBJETOS_DESCOMPILADOS for a20
--SELECT OWNER || ';' || OBJECT_TYPE || ';' || OBJECT_NAME || ';' || LAST_DDL_TIME
--FROM DBA_OBJECTS
--WHERE STATUS != 'VALID'
--and owner not in ('OLAPSYS', 'SYS','SYSTEM','ORDDATA','MDSYS','SYS_CONSULTA','SMARTLOGIC','SYSMAN','PUBLIC','APEX_030200','PERFSTAT' )
--ORDER BY LAST_DDL_TIME;


select owner, object_name, object_type, status FROM dba_objects where status='INVALID';