+===================================================================+
|               CONSULTA PARA VALDIAR INDEX UNUSABLES               |
+===================================================================+

SELECT 'ALTER INDEX ' || OWNER || '.' ||
INDEX_NAME || ' REBUILD ' ||
' TABLESPACE ' || TABLESPACE_NAME || ';'
FROM DBA_INDEXES
WHERE STATUS='UNUSABLE'
UNION
SELECT 'ALTER INDEX ' || INDEX_OWNER || '.' ||
INDEX_NAME ||
' REBUILD PARTITION ' || PARTITION_NAME ||
' TABLESPACE ' || TABLESPACE_NAME || ';'
FROM DBA_IND_PARTITIONS
WHERE STATUS='UNUSABLE'
UNION
SELECT 'ALTER INDEX ' || INDEX_OWNER || '.' ||
INDEX_NAME ||
' REBUILD SUBPARTITION '||SUBPARTITION_NAME||
' TABLESPACE ' || TABLESPACE_NAME || ';'
FROM DBA_IND_SUBPARTITIONS
WHERE STATUS='UNUSABLE';


@11_pmp_index_unusable.sql




+===================================================================+
|                pasar index a USUABLES                             |
+===================================================================+
-- EJEMPLO:
ALTER INDEX ANYSCOL.FAC_JDA_INVENTARIO_NU2 REBUILD ONLINE TABLESPACE ANA_INDEX PARALLEL 4;


----------------------------------------------------------------------------------------------

ALTER INDEX ANYSCOL.FAC_JDA_INVENTARIO_LLAVE_UN_IDX REBUILD ONLINE TABLESPACE ANA_INDEX PARALLEL 4;
ALTER INDEX ANYSCOL.FAC_JDA_INVENTARIO_LLAVE_UN_NU1 REBUILD ONLINE TABLESPACE ANA_INDEX PARALLEL 4;
ALTER INDEX ANYSCOL.FAC_JDA_INVENTARIO_LLAVE_UN__NU2 REBUILD ONLINE TABLESPACE ANA_INDEX PARALLEL 4;
ALTER INDEX ANYSCOL.FAC_JDA_INVENTARIO_NU1 REBUILD  TABLESPACE ONLINE ANA_INDEX PARALLEL 4;
ALTER INDEX ANYSCOL.FAC_JDA_INVENTARIO_NU2 REBUILD  TABLESPACE ONLINE ANA_INDEX PARALLEL 4;
ALTER INDEX ANYSCOL.FAC_JDA_INVENTARIO_NU3 REBUILD  TABLESPACE ONLINE ANA_INDEX PARALLEL 4;
ALTER INDEX ANYSCOL.FAC_JDA_INVENTARIO_NU4 REBUILD  TABLESPACE ONLINE ANA_INDEX PARALLEL 4;
ALTER INDEX ANYSCOL.FAC_JDA_INVENTARIO_NUF1 REBUILD  TABLESPACE ONLINE ANA_INDEX PARALLEL 4;
